import { useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { base44 } from '@/api/base44Client';
import { useQuery } from '@tanstack/react-query';
import { ArrowLeft, FileText, Download, Briefcase } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { createPageUrl } from '../utils';

export default function ClientBriefing() {
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const projectId = searchParams.get('id');
  const [isGenerating, setIsGenerating] = useState(false);

  const { data: project } = useQuery({
    queryKey: ['project', projectId],
    queryFn: async () => {
      const projects = await base44.entities.Project.filter({ id: projectId });
      return projects[0];
    },
    enabled: !!projectId
  });

  const { data: milestones = [] } = useQuery({
    queryKey: ['milestones', projectId],
    queryFn: () => base44.entities.Milestone.filter({ projectId }),
    enabled: !!projectId
  });

  const { data: risks = [] } = useQuery({
    queryKey: ['risks', projectId],
    queryFn: () => base44.entities.Risk.filter({ projectId }),
    enabled: !!projectId
  });

  const { data: latestReport } = useQuery({
    queryKey: ['latest-report', projectId],
    queryFn: async () => {
      const reports = await base44.entities.WeeklyReport.filter({ projectId }, '-weekEnding', 1);
      return reports[0];
    },
    enabled: !!projectId
  });

  const generateBriefing = async () => {
    setIsGenerating(true);
    
    const completedMilestones = milestones.filter(m => m.status === 'Complete').length;
    const totalMilestones = milestones.length;
    const criticalRisks = risks.filter(r => r.riskLevel === 'Critical' && r.status !== 'Closed').length;
    const activeRisks = risks.filter(r => r.status !== 'Closed').length;

    const briefingContent = `
# CLIENT BRIEFING
## ${project.projectName}

**Date:** ${new Date().toLocaleDateString()}
**Client:** ${project.clientName}
**Project Owner:** ${project.projectOwner}

---

## EXECUTIVE SUMMARY

**Overall Health Score:** ${project.healthScore || 0}/100
**Current Phase:** ${project.currentPhase}
**Project Status:** ${project.status}

---

## PROJECT PROGRESS

- **Total Budget:** €${project.totalBudgetEurM}M
- **Start Date:** ${project.startDate ? new Date(project.startDate).toLocaleDateString() : 'Not set'}
- **Target Completion:** ${project.targetCompletion ? new Date(project.targetCompletion).toLocaleDateString() : 'Not set'}
- **Milestones Completed:** ${completedMilestones}/${totalMilestones}

---

## RISK OVERVIEW

- **Total Active Risks:** ${activeRisks}
- **Critical Risks:** ${criticalRisks}
${criticalRisks > 0 ? `- ⚠️ **Action Required:** Critical risks need immediate attention` : '- ✅ No critical risks at this time'}

---

## RECENT HIGHLIGHTS

${latestReport?.highlights?.length > 0 ? latestReport.highlights.map(h => `- ${h}`).join('\n') : '- No recent highlights available'}

---

## UPCOMING ACTIVITIES

${latestReport?.nextWeek?.length > 0 ? latestReport.nextWeek.map(n => `- ${n}`).join('\n') : '- Please refer to detailed project schedule'}

---

*This briefing was automatically generated by the PMO Governance Platform*
    `;

    const blob = new Blob([briefingContent], { type: 'text/markdown' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Client-Briefing-${project.projectName.replace(/\s+/g, '-')}-${new Date().toISOString().split('T')[0]}.md`;
    document.body.appendChild(a);
    a.click();
    window.URL.revokeObjectURL(url);
    a.remove();

    setIsGenerating(false);
  };

  if (!project) {
    return (
      <div className="min-h-screen flex items-center justify-center" style={{ background: 'linear-gradient(135deg, #1E2761 0%, #0F172A 100%)' }}>
        <p style={{ color: '#94A3B8' }}>Loading...</p>
      </div>
    );
  }

  const completedMilestones = milestones.filter(m => m.status === 'Complete').length;
  const totalMilestones = milestones.length;
  const criticalRisks = risks.filter(r => r.riskLevel === 'Critical' && r.status !== 'Closed').length;

  return (
    <div className="min-h-screen" style={{ background: 'linear-gradient(135deg, #1E2761 0%, #0F172A 100%)' }}>
      <div style={{ background: 'rgba(15, 23, 42, 0.95)', borderBottom: '1px solid rgba(202, 220, 252, 0.1)' }} className="shadow-sm">
        <div className="max-w-7xl mx-auto px-6 py-6">
          <Button
            variant="ghost"
            onClick={() => navigate(createPageUrl(`ProjectDashboard?id=${projectId}`))}
            className="mb-4"
            style={{ color: '#CADCFC' }}
          >
            <ArrowLeft className="w-4 h-4 mr-2" />
            Back to Tools
          </Button>
          <div className="flex items-center justify-between">
            <div>
              <h1 className="text-3xl font-bold" style={{ color: '#CADCFC' }}>Client Briefing</h1>
              <p className="mt-2" style={{ color: '#94A3B8' }}>Generate executive summaries for stakeholders</p>
            </div>
            <Button 
              onClick={generateBriefing} 
              disabled={isGenerating}
              style={{ background: 'linear-gradient(135deg, #028090 0%, #00A896 100%)', color: '#F8FAFC' }}
            >
              <Download className="w-4 h-4 mr-2" />
              {isGenerating ? 'Generating...' : 'Generate Briefing'}
            </Button>
          </div>
        </div>
      </div>

      <div className="max-w-4xl mx-auto px-6 py-8">
        <Card style={{ background: 'rgba(30, 39, 97, 0.5)', borderColor: 'rgba(202, 220, 252, 0.1)' }} className="mb-6">
          <CardHeader>
            <CardTitle style={{ color: '#CADCFC' }}>Briefing Preview</CardTitle>
          </CardHeader>
          <CardContent className="space-y-6">
            <div>
              <h3 className="text-xl font-semibold mb-2" style={{ color: '#CADCFC' }}>{project.projectName}</h3>
              <div className="grid grid-cols-2 gap-4 text-sm">
                <div>
                  <span style={{ color: '#94A3B8' }}>Client: </span>
                  <span style={{ color: '#F8FAFC' }}>{project.clientName}</span>
                </div>
                <div>
                  <span style={{ color: '#94A3B8' }}>Owner: </span>
                  <span style={{ color: '#F8FAFC' }}>{project.projectOwner}</span>
                </div>
              </div>
            </div>

            <div className="pt-4 border-t" style={{ borderColor: 'rgba(202, 220, 252, 0.1)' }}>
              <h4 className="font-semibold mb-3" style={{ color: '#CADCFC' }}>Executive Summary</h4>
              <div className="grid grid-cols-3 gap-4">
                <div className="text-center p-4 rounded-lg" style={{ background: 'rgba(15, 23, 42, 0.5)' }}>
                  <div className="text-3xl font-bold" style={{ color: '#10B981' }}>{project.healthScore || 0}</div>
                  <div className="text-sm mt-1" style={{ color: '#94A3B8' }}>Health Score</div>
                </div>
                <div className="text-center p-4 rounded-lg" style={{ background: 'rgba(15, 23, 42, 0.5)' }}>
                  <div className="text-3xl font-bold" style={{ color: '#CADCFC' }}>{completedMilestones}/{totalMilestones}</div>
                  <div className="text-sm mt-1" style={{ color: '#94A3B8' }}>Milestones</div>
                </div>
                <div className="text-center p-4 rounded-lg" style={{ background: 'rgba(15, 23, 42, 0.5)' }}>
                  <div className={`text-3xl font-bold ${criticalRisks > 0 ? 'text-red-500' : ''}`} style={{ color: criticalRisks > 0 ? undefined : '#CADCFC' }}>{criticalRisks}</div>
                  <div className="text-sm mt-1" style={{ color: '#94A3B8' }}>Critical Risks</div>
                </div>
              </div>
            </div>

            {latestReport && (
              <div className="pt-4 border-t" style={{ borderColor: 'rgba(202, 220, 252, 0.1)' }}>
                <h4 className="font-semibold mb-3" style={{ color: '#CADCFC' }}>Latest Update</h4>
                <div className="text-sm" style={{ color: '#94A3B8' }}>
                  Week ending: {new Date(latestReport.weekEnding).toLocaleDateString()}
                </div>
                {latestReport.highlights?.length > 0 && (
                  <div className="mt-3">
                    <div className="font-medium mb-1" style={{ color: '#CADCFC' }}>Highlights:</div>
                    <ul className="list-disc list-inside space-y-1" style={{ color: '#94A3B8' }}>
                      {latestReport.highlights.slice(0, 3).map((h, i) => <li key={i}>{h}</li>)}
                    </ul>
                  </div>
                )}
              </div>
            )}
          </CardContent>
        </Card>

        <Card style={{ background: 'rgba(30, 39, 97, 0.5)', borderColor: 'rgba(202, 220, 252, 0.1)' }}>
          <CardContent className="p-8 text-center">
            <Briefcase className="w-12 h-12 mx-auto mb-4" style={{ color: '#028090' }} />
            <h3 className="text-lg font-semibold mb-2" style={{ color: '#CADCFC' }}>One-Click Executive Summary</h3>
            <p className="mb-4" style={{ color: '#94A3B8' }}>
              Generate a comprehensive briefing document that includes project status, milestones, risks, and recent highlights.
            </p>
            <p className="text-sm" style={{ color: '#94A3B8' }}>
              The briefing will be downloaded as a Markdown file that can be shared with stakeholders.
            </p>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}