// Site Selection — Criteria Definitions
// All 6 categories with their criteria, requirements, and keys

export const CATEGORIES = [
  {
    id: 'ownership',
    label: '1. Ownership & Development',
    weight: 10,
    criteria: [
      { key: '1.1', label: 'Site name', requirement: '—' },
      { key: '1.2', label: 'Address', requirement: '—' },
      { key: '1.3', label: 'Owner type (Private/Public/Mixed)', requirement: '—' },
      { key: '1.4', label: 'Sale vs. Lease', requirement: 'Sale or Lease' },
      { key: '1.5', label: 'Owner agreement to sell/lease', requirement: 'Yes' },
      { key: '1.6', label: 'Impediments to sale', requirement: 'No' },
      { key: '1.7', label: 'Estimated timeline to transfer (MM/YYYY)', requirement: 'TBD' },
      { key: '1.8', label: 'Asking price (€/m²)', requirement: '—' },
      { key: '1.9', label: 'Former / current use', requirement: '—' },
      { key: '1.10', label: 'Neighboring use', requirement: '—' },
      { key: '1.11', label: 'Compensation area required (% of total)', requirement: '—' },
      { key: '1.12', label: 'Land development plan in place (MM/YYYY)', requirement: 'TBD' },
      { key: '1.13', label: 'Turn-key land preparation offered', requirement: '—' },
    ]
  },
  {
    id: 'plot',
    label: '2. Plot Characteristics',
    weight: 20,
    criteria: [
      { key: '2.1', label: 'Total site area (hectares)', requirement: 'User-defined' },
      { key: '2.2', label: 'Min production building footprint (L×W m)', requirement: 'User-defined' },
      { key: '2.3', label: 'Flexibility to purchase partial plot', requirement: '—' },
      { key: '2.4', label: 'Possibility for future extension', requirement: '—' },
      { key: '2.5', label: 'Zoned for industrial/production use', requirement: 'Yes' },
      { key: '2.6', label: 'Ready for construction start (Quarter/Year)', requirement: 'User-defined' },
      { key: '2.7', label: 'Floor area ratio', requirement: 'User-defined' },
      { key: '2.8', label: 'Maximum building height allowed (m)', requirement: 'User-defined' },
      { key: '2.9', label: 'Ground slope', requirement: 'Preferred flat' },
      { key: '2.10', label: 'Ground type / bearing capacity', requirement: 'Survey required' },
      { key: '2.11', label: 'Road weight bearing capacity (tonnes)', requirement: 'Min 40t' },
      { key: '2.12', label: 'Water table depth (m)', requirement: '—' },
      { key: '2.13', label: 'Seismic risk level', requirement: 'No' },
      { key: '2.14', label: 'Within flood zone', requirement: 'No' },
      { key: '2.15', label: 'Wetlands present', requirement: 'No' },
      { key: '2.16', label: 'Protected flora/fauna requiring relocation', requirement: 'No' },
      { key: '2.17', label: 'Historical/cultural artifacts present', requirement: 'No' },
      { key: '2.18', label: 'Endangered species present', requirement: 'No' },
      { key: '2.19', label: 'Underground storage tanks present', requirement: 'No' },
      { key: '2.20', label: '24/7 operations permitted', requirement: 'Yes' },
      { key: '2.21', label: 'Geological survey available', requirement: 'Yes' },
      { key: '2.22', label: 'Geodesic survey available', requirement: 'Yes' },
      { key: '2.23', label: 'Environmental survey available', requirement: 'Yes' },
      { key: '2.24', label: 'Stormwater drainage plan', requirement: 'Yes' },
      { key: '2.25', label: 'Air quality report available', requirement: 'Yes' },
      { key: '2.26', label: 'Noise limits during construction', requirement: '—' },
      { key: '2.27', label: 'Noise limits during operation', requirement: '—' },
      { key: '2.28', label: 'Distance to nearest fire station (km)', requirement: 'As close as possible' },
      { key: '2.29', label: 'Permitting constraints or risks', requirement: '—' },
      { key: '2.30', label: 'Permit authority (levelling & building)', requirement: '—' },
      { key: '2.31', label: 'Estimated permitting timeline (months)', requirement: '—' },
    ]
  },
  {
    id: 'utilities',
    label: '3. Utilities',
    weight: 20,
    criteria: [
      { key: '3.1', label: 'Transmission line voltage available', requirement: 'Yes' },
      { key: '3.2', label: 'Existing grid connection to site', requirement: 'Yes' },
      { key: '3.3', label: 'Total substation capacity (MW)', requirement: 'User-defined' },
      { key: '3.4', label: 'Timeline to upgrade grid connection', requirement: '—' },
      { key: '3.5', label: 'Direct renewable energy connection (Wind)', requirement: '—' },
      { key: '3.6', label: 'Direct renewable energy connection (Solar)', requirement: '—' },
      { key: '3.7', label: 'PPA / Green energy partnership possible', requirement: '—' },
      { key: '3.8', label: 'Electricity cost (€/MWh)', requirement: '—' },
      { key: '3.9', label: 'Heat exchange possibility', requirement: '—' },
      { key: '3.10', label: 'Gas supply available', requirement: '—' },
      { key: '3.11', label: 'Gas cost (€/MWh)', requirement: '—' },
      { key: '3.12', label: 'Water connection to site', requirement: 'Yes' },
      { key: '3.13', label: 'Freshwater supply capacity (m³/year)', requirement: 'User-defined' },
      { key: '3.14', label: 'Freshwater price (€/m³)', requirement: '—' },
      { key: '3.15', label: 'Potable water supply capacity (m³/day)', requirement: 'User-defined' },
      { key: '3.16', label: 'Potable water price (€/m³)', requirement: '—' },
      { key: '3.17', label: 'Cooling water available', requirement: '—' },
      { key: '3.18', label: 'Cooling water capacity (m³/h)', requirement: '—' },
      { key: '3.19', label: 'Existing wastewater treatment (WWTP)', requirement: 'Yes' },
      { key: '3.20', label: 'Distance to WWTP (km)', requirement: '—' },
      { key: '3.21', label: 'WWTP capacity (m³/day)', requirement: 'User-defined' },
      { key: '3.22', label: 'WWTP connection timeline', requirement: '—' },
      { key: '3.23', label: 'Max contamination limits for WWTP discharge', requirement: '—' },
      { key: '3.24', label: 'WWTP discharge cost (€/m³)', requirement: '—' },
    ]
  },
  {
    id: 'infrastructure',
    label: '4. Infrastructure & Access',
    weight: 15,
    criteria: [
      { key: '4.1', label: 'Distance to port (km)', requirement: '—' },
      { key: '4.2', label: 'Port capacity (containers/year)', requirement: '—' },
      { key: '4.3', label: 'Distance to regional airport (km)', requirement: '< 50 km' },
      { key: '4.4', label: 'Distance to international airport (km)', requirement: '< 100 km' },
      { key: '4.5', label: 'Direct rail connection', requirement: 'Possible' },
      { key: '4.6', label: 'Distance to nearest rail line (km)', requirement: '—' },
      { key: '4.7', label: 'Timeline to connect to rail network', requirement: '—' },
      { key: '4.8', label: 'Industrial grade access road exists', requirement: 'Yes' },
      { key: '4.9', label: 'Timeline for road connection', requirement: '—' },
      { key: '4.10', label: 'Distance to highway (km)', requirement: '< 5 km' },
      { key: '4.11', label: 'Broadband internet available', requirement: 'Yes' },
      { key: '4.12', label: 'High-speed fibre capacity (Gbit/s)', requirement: 'User-defined' },
      { key: '4.13', label: 'Timeline for internet upgrade', requirement: '—' },
      { key: '4.14', label: 'Access to international schools', requirement: '—' },
      { key: '4.15', label: 'Public transport / commuting services', requirement: '—' },
      { key: '4.16', label: 'Housing availability (apartments within 15 km)', requirement: '—' },
      { key: '4.17', label: 'Housing growth plan (additional units planned)', requirement: '—' },
    ]
  },
  {
    id: 'workforce',
    label: '5. Workforce & Labour Market',
    weight: 20,
    criteria: [
      { key: '5.1', label: 'Regional crime rate (per 100k inhabitants)', requirement: '—' },
      { key: '5.2', label: 'Average age of population', requirement: '—' },
      { key: '5.3', label: 'Working age population 15-64 (%)', requirement: '—' },
      { key: '5.4', label: 'Population growth (5-year avg %)', requirement: '—' },
      { key: '5.5', label: 'Net immigration (2-year avg %)', requirement: '—' },
      { key: '5.6', label: 'GDP per capita (€/person)', requirement: '—' },
      { key: '5.7', label: 'Patent applications (per region)', requirement: '—' },
      { key: '5.8', label: 'Distance to closest residential area (km)', requirement: '—' },
      { key: '5.9', label: 'Distance to nearest city >10k pop (km)', requirement: '—' },
      { key: '5.10', label: 'Distance to metropolitan area >200k (km)', requirement: '< 70 km' },
      { key: '5.11', label: 'Commute time to metro (public transport, min)', requirement: '< 45 min' },
      { key: '5.12', label: 'Regional unemployment rate (%)', requirement: '—' },
      { key: '5.13', label: 'Total unemployed workforce in region', requirement: '—' },
      { key: '5.14', label: 'Average operator wage, excl. social (€/month)', requirement: '—' },
      { key: '5.15', label: 'Relevant training programs (blue collar graduates)', requirement: '—' },
      { key: '5.16', label: 'Average engineer wage, excl. social (€/month)', requirement: '—' },
      { key: '5.17', label: 'Relevant university programs (white collar graduates)', requirement: '—' },
      { key: '5.18', label: 'Relevant companies / industrial cluster within 50 km', requirement: '—' },
    ]
  },
  {
    id: 'incentives',
    label: '6. Incentives & Support',
    weight: 15,
    criteria: [
      { key: '6.1', label: 'Government grants available', requirement: '—' },
      { key: '6.2', label: 'Grant type', requirement: '—' },
      { key: '6.3', label: 'Estimated grant amount (€M)', requirement: '—' },
      { key: '6.4', label: 'Grant application timeline (months)', requirement: '—' },
      { key: '6.5', label: 'Tax incentives available', requirement: '—' },
      { key: '6.6', label: 'Corporate tax rate (%)', requirement: '—' },
      { key: '6.7', label: 'Free trade zone / special economic zone', requirement: '—' },
      { key: '6.8', label: 'Subsidized land / reduced price offered', requirement: '—' },
      { key: '6.9', label: 'Training subsidies available', requirement: '—' },
      { key: '6.10', label: 'Local government support level', requirement: '—' },
      { key: '6.11', label: 'One-stop-shop / dedicated point of contact', requirement: '—' },
      { key: '6.12', label: 'Existing partnership / cluster synergies', requirement: '—' },
    ]
  },
];

export const DEFAULT_WEIGHTS = {
  ownership: 10,
  plot: 20,
  utilities: 20,
  infrastructure: 15,
  workforce: 20,
  incentives: 15,
};

export const MEETS_COLORS = {
  Yes: 'text-green-400',
  Partial: 'text-yellow-400',
  No: 'text-red-400',
  'N/A': 'text-gray-400',
  TBD: 'text-gray-500',
};

export const MEETS_ICONS = {
  Yes: '✅',
  Partial: '⚠️',
  No: '❌',
  'N/A': '⬜',
  TBD: '⬜',
};