export const NEURON_SEEDS = [
  { module_key: 'site_selection',    display_name: 'Site Selection',    short_code: 'SITE',  icon: '🗺️',  color: '#8b5cf6', category: 'Core',         description: 'Site evaluation, scoring, comparison and selection workflows', position_x: 0.12, position_y: 0.25, is_active: true, health_status: 'Healthy', pulse_count_24h: 18 },
  { module_key: 'finance_model',     display_name: 'Finance Model',     short_code: 'FIN',   icon: '💰',  color: '#10b981', category: 'Core',         description: 'Financial modelling, CAPEX, NPV, IRR, DCF and cash flow projections', position_x: 0.35, position_y: 0.15, is_active: true, health_status: 'Healthy', pulse_count_24h: 42 },
  { module_key: 'feasibility_study', display_name: 'Feasibility Study', short_code: 'FEAS',  icon: '📊',  color: '#f59e0b', category: 'Core',         description: 'Feasibility analysis, study management and go/no-go decisions', position_x: 0.60, position_y: 0.12, is_active: true, health_status: 'Healthy', pulse_count_24h: 24 },
  { module_key: 'master_schedule',   display_name: 'Master Schedule',   short_code: 'SCHED', icon: '📅',  color: '#3b82f6', category: 'Core',         description: 'Master project schedule, milestones, WBS and progress tracking', position_x: 0.82, position_y: 0.22, is_active: true, health_status: 'Healthy', pulse_count_24h: 31 },
  { module_key: 'p6_msp_sync',       display_name: 'P6 / MSP Sync',    short_code: 'P6',    icon: '📥',  color: '#06b6d4', category: 'Integration',  description: 'Primavera P6 and Microsoft Project schedule import and sync', position_x: 0.90, position_y: 0.42, is_active: true, health_status: 'Healthy', pulse_count_24h: 8  },
  { module_key: 'change_management', display_name: 'Change Management', short_code: 'CR',    icon: '🔄',  color: '#f97316', category: 'Governance',   description: 'Change requests, impact assessments and approval workflows', position_x: 0.78, position_y: 0.60, is_active: true, health_status: 'Healthy', pulse_count_24h: 15 },
  { module_key: 'action_tracker',    display_name: 'Action Tracker',    short_code: 'ACT',   icon: '📋',  color: '#ef4444', category: 'Governance',   description: 'Action items, issues, decisions, RFIs and blockers', position_x: 0.55, position_y: 0.72, is_active: true, health_status: 'Healthy', pulse_count_24h: 56 },
  { module_key: 'weekly_report',     display_name: 'Weekly Report',     short_code: 'WR',    icon: '📰',  color: '#0ea5e9', category: 'Output',       description: 'Weekly project reports with RAG status and narrative sections', position_x: 0.32, position_y: 0.80, is_active: true, health_status: 'Healthy', pulse_count_24h: 12 },
  { module_key: 'daily_site_report', display_name: 'Daily Site Report', short_code: 'DSR',   icon: '🏗️',  color: '#84cc16', category: 'Output',       description: 'Daily on-site progress, workforce and equipment reports', position_x: 0.12, position_y: 0.70, is_active: true, health_status: 'Healthy', pulse_count_24h: 28 },
  { module_key: 'quality_gates',     display_name: 'Quality Gates',     short_code: 'GATE',  icon: '🚩',  color: '#ec4899', category: 'Governance',   description: 'Gate reviews, readiness assessments and go/no-go decisions', position_x: 0.10, position_y: 0.50, is_active: true, health_status: 'Healthy', pulse_count_24h: 9  },
  { module_key: 'ai_agent',          display_name: 'AI Agent',          short_code: 'AI',    icon: '🤖',  color: '#a78bfa', category: 'Intelligence', description: 'AI-powered analysis, narrative generation and platform intelligence', position_x: 0.50, position_y: 0.45, is_active: true, health_status: 'Healthy', pulse_count_24h: 88 },
  { module_key: 'platform_home',     display_name: 'Platform Home',     short_code: 'HOME',  icon: '🏠',  color: '#64748b', category: 'Output',       description: 'Platform dashboard, KPI display and project overview', position_x: 0.28, position_y: 0.48, is_active: true, health_status: 'Healthy', pulse_count_24h: 142 },
];

export const SYNAPSE_SEEDS = (neurons) => {
  const n = {};
  neurons.forEach(neuron => { n[neuron.module_key] = neuron.id; });
  return [
    // Site Selection → Finance Model
    { from_neuron_id: n['site_selection'], to_neuron_id: n['finance_model'], synapse_name: 'Site cost assumptions', synapse_type: 'One-Way', priority: 'High', is_active: true, is_critical: true, health_status: 'Active', trigger_type: 'On Event', trigger_event: 'on_site_evaluation_complete', source_entity: 'CandidateSite', source_fields: '["land_cost","utility_rates","labor_rates","site_area"]', processing_rules: JSON.stringify([{ rule_type: 'Transform', rule_name: 'Normalize currency', description: 'Convert all costs to EUR millions' }]), fire_count_24h: 2 },
    // Site Selection → Feasibility Study
    { from_neuron_id: n['site_selection'], to_neuron_id: n['feasibility_study'], synapse_name: 'Site scores to feasibility', synapse_type: 'One-Way', priority: 'High', is_active: true, is_critical: false, health_status: 'Active', trigger_type: 'On Event', trigger_event: 'on_site_scoring_complete', source_entity: 'SiteAssessment', source_fields: '["overall_score","technical_score","cost_score","risk_score"]', processing_rules: JSON.stringify([{ rule_type: 'Filter', rule_name: 'Top 3 sites only', description: 'Only pass sites with score > 70' }]), fire_count_24h: 1 },
    // Finance Model → Feasibility Study
    { from_neuron_id: n['finance_model'], to_neuron_id: n['feasibility_study'], synapse_name: 'Financial metrics', synapse_type: 'One-Way', priority: 'High', is_active: true, is_critical: true, health_status: 'Active', trigger_type: 'On Event', trigger_event: 'on_model_approval', source_entity: 'FinanceModel', source_fields: '["npv","irr","payback_period","total_capex","contingency_pct"]', processing_rules: JSON.stringify([{ rule_type: 'Formula', rule_name: 'Calculate investment score', description: 'NPV/CAPEX ratio' }, { rule_type: 'Conditional', rule_name: 'Set viability flag', description: 'IRR > 15% = Viable' }]), fire_count_24h: 3 },
    // Finance Model → Change Management (budget thresholds)
    { from_neuron_id: n['finance_model'], to_neuron_id: n['change_management'], synapse_name: 'Budget thresholds', synapse_type: 'One-Way', priority: 'High', is_active: true, is_critical: true, health_status: 'Active', trigger_type: 'Real-time', source_entity: 'FinanceModel', source_fields: '["contingency_total","contingency_remaining","total_capex"]', processing_rules: JSON.stringify([{ rule_type: 'Formula', rule_name: 'Contingency pct', description: '(remaining/total)*100' }, { rule_type: 'Alert', rule_name: 'Low contingency warning', description: 'Alert if contingency < 50%' }]), fire_count_24h: 6 },
    // Finance Model → Weekly Report (cost section)
    { from_neuron_id: n['finance_model'], to_neuron_id: n['weekly_report'], synapse_name: 'Cost section data', synapse_type: 'One-Way', priority: 'High', is_active: true, is_critical: true, health_status: 'Active', trigger_type: 'On Event', trigger_event: 'on_report_generation', trigger_condition: "report.type == 'Weekly'", source_entity: 'FinanceModel', source_fields: '["npv","irr","total_capex","capex_spent","contingency_total","contingency_remaining"]', processing_rules: JSON.stringify([{ rule_type: 'Formula', rule_name: 'Budget variance', description: 'total_capex - capex_spent' }, { rule_type: 'Conditional', rule_name: 'Set cost RAG', description: 'budget_pct > 100 → Red' }, { rule_type: 'Format', rule_name: 'Format display', description: 'Budget: $X | Spent: $Y (Z%)' }]), fire_count_24h: 4 },
    // Finance Model → Platform Home
    { from_neuron_id: n['finance_model'], to_neuron_id: n['platform_home'], synapse_name: 'Financial KPIs', synapse_type: 'One-Way', priority: 'Medium', is_active: true, is_critical: false, health_status: 'Active', trigger_type: 'Scheduled', trigger_schedule: 'every_hour', source_entity: 'FinanceModel', source_fields: '["npv","irr","total_capex","capex_spent"]', processing_rules: JSON.stringify([{ rule_type: 'Format', rule_name: 'KPI cards', description: 'Format for dashboard display' }]), fire_count_24h: 24 },
    // Master Schedule → Weekly Report
    { from_neuron_id: n['master_schedule'], to_neuron_id: n['weekly_report'], synapse_name: 'Schedule section data', synapse_type: 'One-Way', priority: 'High', is_active: true, is_critical: true, health_status: 'Active', trigger_type: 'On Event', trigger_event: 'on_report_generation', source_entity: 'Milestone', source_fields: '["phaseName","status","dueDate","completionPercent"]', processing_rules: JSON.stringify([{ rule_type: 'Aggregate', rule_name: 'Phase completion', description: 'AVG completion per phase' }, { rule_type: 'Conditional', rule_name: 'Set schedule RAG', description: 'Overdue milestones → Red' }]), fire_count_24h: 4 },
    // Master Schedule → Platform Home
    { from_neuron_id: n['master_schedule'], to_neuron_id: n['platform_home'], synapse_name: 'Schedule KPIs', synapse_type: 'One-Way', priority: 'Medium', is_active: true, is_critical: false, health_status: 'Active', trigger_type: 'Scheduled', trigger_schedule: 'every_hour', source_entity: 'Milestone', source_fields: '["status","dueDate","phaseName"]', processing_rules: JSON.stringify([{ rule_type: 'Aggregate', rule_name: 'Next milestone', description: 'Find earliest upcoming milestone' }]), fire_count_24h: 24 },
    // Master Schedule → Change Management (schedule impacts)
    { from_neuron_id: n['master_schedule'], to_neuron_id: n['change_management'], synapse_name: 'Schedule baseline', synapse_type: 'One-Way', priority: 'High', is_active: true, is_critical: false, health_status: 'Active', trigger_type: 'On Record Change', source_entity: 'ScheduleTask', source_fields: '["plannedFinish","baselineFinish","isCritical","totalFloat"]', processing_rules: JSON.stringify([{ rule_type: 'Formula', rule_name: 'Variance days', description: 'planned - baseline' }, { rule_type: 'Filter', rule_name: 'Critical path only', description: 'isCritical = true OR totalFloat < 10' }]), fire_count_24h: 8 },
    // P6 Sync → Master Schedule
    { from_neuron_id: n['p6_msp_sync'], to_neuron_id: n['master_schedule'], synapse_name: 'Schedule import', synapse_type: 'One-Way', priority: 'High', is_active: true, is_critical: true, health_status: 'Active', trigger_type: 'On Event', trigger_event: 'on_schedule_import', source_entity: 'ScheduleTask', source_fields: '["taskName","plannedStart","plannedFinish","percentComplete","totalFloat","isCritical"]', processing_rules: JSON.stringify([{ rule_type: 'Validate', rule_name: 'Date validation', description: 'Ensure dates are valid and not in past' }, { rule_type: 'Transform', rule_name: 'WBS mapping', description: 'Map external WBS to unified WBS' }]), fire_count_24h: 1 },
    // Change Management → Action Tracker
    { from_neuron_id: n['change_management'], to_neuron_id: n['action_tracker'], synapse_name: 'CR implementation actions', synapse_type: 'One-Way', priority: 'High', is_active: true, is_critical: false, health_status: 'Active', trigger_type: 'On Event', trigger_event: 'on_cr_approval', trigger_condition: "cr.status == 'Approved'", source_entity: 'ChangeRequest', source_fields: '["title","category","priority","requiredByDate","raisedBy"]', processing_rules: JSON.stringify([{ rule_type: 'Transform', rule_name: 'Create action item', description: 'Map CR to ActionItem fields' }, { rule_type: 'Enrich', rule_name: 'Add CR reference', description: 'Link action to CR number' }]), fire_count_24h: 3 },
    // Change Management → Weekly Report
    { from_neuron_id: n['change_management'], to_neuron_id: n['weekly_report'], synapse_name: 'CR summary', synapse_type: 'One-Way', priority: 'Medium', is_active: true, is_critical: false, health_status: 'Active', trigger_type: 'On Event', trigger_event: 'on_report_generation', source_entity: 'ChangeRequest', source_fields: '["status","category","priority","capexImpact"]', source_filter: "status NOT IN ('Closed','Withdrawn')", processing_rules: JSON.stringify([{ rule_type: 'Aggregate', rule_name: 'CR stats', description: 'COUNT by status, SUM capex impact' }, { rule_type: 'Format', rule_name: 'CR section text', description: 'X open CRs, $Y total impact' }]), fire_count_24h: 4 },
    // Change Management → Finance Model (approved cost impacts)
    { from_neuron_id: n['change_management'], to_neuron_id: n['finance_model'], synapse_name: 'Approved cost impacts', synapse_type: 'One-Way', priority: 'High', is_active: true, is_critical: true, health_status: 'Active', trigger_type: 'On Event', trigger_event: 'on_cr_approval', trigger_condition: "cr.capexImpact != 0", source_entity: 'ChangeImpactAssessment', source_fields: '["capexImpactUsd","contingencyDrawUsd","fundingSource"]', processing_rules: JSON.stringify([{ rule_type: 'Formula', rule_name: 'Update forecast', description: 'Add approved capex impact to total' }]), fire_count_24h: 2 },
    // Action Tracker → Weekly Report
    { from_neuron_id: n['action_tracker'], to_neuron_id: n['weekly_report'], synapse_name: 'Action summary', synapse_type: 'One-Way', priority: 'Medium', is_active: true, is_critical: false, health_status: 'Active', trigger_type: 'On Event', trigger_event: 'on_report_generation', source_entity: 'ActionItem', source_fields: '["status","priority","dueDate","assignee","blocked"]', source_filter: "archived = false", processing_rules: JSON.stringify([{ rule_type: 'Aggregate', rule_name: 'Action stats', description: 'COUNT by status and priority' }, { rule_type: 'Filter', rule_name: 'Overdue filter', description: 'dueDate < today AND status != Done' }, { rule_type: 'Format', rule_name: 'Actions section', description: 'X open, Y overdue, Z blocked' }]), fire_count_24h: 4 },
    // Action Tracker → Platform Home
    { from_neuron_id: n['action_tracker'], to_neuron_id: n['platform_home'], synapse_name: 'Action KPIs', synapse_type: 'One-Way', priority: 'Low', is_active: true, is_critical: false, health_status: 'Active', trigger_type: 'Scheduled', trigger_schedule: 'every_30_minutes', source_entity: 'ActionItem', source_fields: '["status","priority","dueDate"]', processing_rules: JSON.stringify([{ rule_type: 'Aggregate', rule_name: 'Open count', description: 'COUNT open and blocked items' }]), fire_count_24h: 48 },
    // Quality Gates → Feasibility Study
    { from_neuron_id: n['quality_gates'], to_neuron_id: n['feasibility_study'], synapse_name: 'Gate status', synapse_type: 'One-Way', priority: 'High', is_active: true, is_critical: false, health_status: 'Active', trigger_type: 'On Record Change', source_entity: 'QualityGate', source_fields: '["gateNumber","gateName","status","decisionDate"]', processing_rules: JSON.stringify([{ rule_type: 'Filter', rule_name: 'Active gates', description: 'Only Active and Passed gates' }]), fire_count_24h: 2 },
    // Quality Gates → Weekly Report
    { from_neuron_id: n['quality_gates'], to_neuron_id: n['weekly_report'], synapse_name: 'Gate readiness', synapse_type: 'One-Way', priority: 'Medium', is_active: true, is_critical: false, health_status: 'Active', trigger_type: 'On Event', trigger_event: 'on_report_generation', source_entity: 'QualityGate', source_fields: '["gateNumber","gateName","status","decisionDate","reserves"]', processing_rules: JSON.stringify([{ rule_type: 'Filter', rule_name: 'Next active gate', description: 'Status = Active' }, { rule_type: 'Format', rule_name: 'Gate section', description: 'Gate X: Status — N days remaining' }]), fire_count_24h: 4 },
    // AI Agent → Weekly Report
    { from_neuron_id: n['ai_agent'], to_neuron_id: n['weekly_report'], synapse_name: 'AI narrative generation', synapse_type: 'Bidirectional', priority: 'High', is_active: true, is_critical: false, health_status: 'Active', trigger_type: 'On Event', trigger_event: 'on_report_generation', source_entity: 'WeeklyReport', source_fields: '["executiveSummary","highlights","concerns","nextWeekFocus","overallRag"]', processing_rules: JSON.stringify([{ rule_type: 'Enrich', rule_name: 'Pull all section data', description: 'Gather data from all other synapses' }, { rule_type: 'Formula', rule_name: 'Generate narrative', description: 'LLM generates executive summary' }]), fire_count_24h: 12 },
    // AI Agent → Platform Home
    { from_neuron_id: n['ai_agent'], to_neuron_id: n['platform_home'], synapse_name: 'AI insights', synapse_type: 'One-Way', priority: 'Low', is_active: true, is_critical: false, health_status: 'Active', trigger_type: 'Scheduled', trigger_schedule: 'daily_06:00', source_entity: 'Project', source_fields: '["healthScore","currentPhase","status"]', processing_rules: JSON.stringify([{ rule_type: 'Formula', rule_name: 'Health trend', description: 'Compare last 4 weeks health scores' }, { rule_type: 'Format', rule_name: 'Insight text', description: 'Plain-English health summary' }]), fire_count_24h: 1 },
    // Daily Site Report → Weekly Report
    { from_neuron_id: n['daily_site_report'], to_neuron_id: n['weekly_report'], synapse_name: 'Site activity rollup', synapse_type: 'One-Way', priority: 'Medium', is_active: true, is_critical: false, health_status: 'Active', trigger_type: 'On Event', trigger_event: 'on_report_generation', source_entity: 'DailySiteReport', source_fields: '["reportDate","workforce_total","activities_completed","weather_impact","safety_incidents"]', source_filter: "reportDate >= report_week_start", processing_rules: JSON.stringify([{ rule_type: 'Aggregate', rule_name: 'Weekly rollup', description: 'SUM workforce, COUNT activities per week' }, { rule_type: 'Conditional', rule_name: 'Safety flag', description: 'incidents > 0 → Amber flag' }]), fire_count_24h: 4 },
  ].filter(s => s.from_neuron_id && s.to_neuron_id);
};